Blog/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import patterns, include, url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('blog.urls', namespace='index')),

]

blog/urls.py
from django.conf.urls import patterns, include, url
from blog.views import *
from blog.models import *


urlpatterns = patterns('',
   url(r'^post/(?P<id_post>\d+)/$', 
       'blog.views.post', 
       name='post'),
   url(r"", "blog.views.index"),
)

blog/models.py
# -*- encoding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin
from django.core.mail import send_mail
from django import forms

#notify = False

class Post(models.Model):
    title = models.CharField(max_length=60)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    nombre_imagen = models.CharField(max_length=80, default= 'noimagen.png')
    url_post=models.CharField(max_length=60, null=True,blank=True)
    
    def __str__(self):
        return self.title




### Admin

class PostAdmin(admin.ModelAdmin):
    search_fields = ["title"]
    display_fields = ["title", "created","categorias","nombre_imagen","imagen",]
    
#NO IMPLEMENTADO    
class Comment(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=60)
    body = models.TextField()
    post = models.ForeignKey(Post)

    def __unicode__(self):
        return unicode("%s: %s" % (self.post, self.body[:60]))

blog/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.template import RequestContext
import time
from calendar import month_name

from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render_to_response
from django.contrib.auth.decorators import login_required
from django.core.context_processors import csrf
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.core.urlresolvers import reverse
from django.template import RequestContext

from blog.models import *
from django.forms import ModelForm
from django.template import loader

# Create your views here.



def index(request):
    """Main listing."""
    context = RequestContext(request)
    posts = Post.objects.all().order_by("-created")
    paginator = Paginator(posts, 5)
    try: page = int(request.GET.get("page", '1'))
    except ValueError: page = 1

    try:
        posts = paginator.page(page)
    except (InvalidPage, EmptyPage):
        posts = paginator.page(paginator.num_pages)

    context.update(dict(posts=posts, user=request.user,
                        post_list=posts.object_list, months=mkmonth_lst()))
    return render_to_response("list.html", context)





def post(request, id_post):
    """Single post with comments and a comment form."""
    context = RequestContext(request)
    post = Post.objects.get(pk=id_post)
    print (request.method)
    if 'POST' in request.method:
        author = request.POST['author']
        content = request.POST['content']
        comentario = Comment(author=author, 
                             body=content,
                             post=post)
        comentario.save()
    comments = Comment.objects.filter(post=post)
    #form=CommentForm()
    context.update(dict(post=post, user=request.user, comments=comments))#, comments=comments)
    context.update(csrf(request))
    return render_to_response("post.html", context)








def mkmonth_lst():
    """Make a list of months to show archive links."""
    if not Post.objects.count(): return []

    # set up vars
    year, month = time.localtime()[:2]
    first = Post.objects.order_by("created")[0]
    fyear = first.created.year
    fmonth = first.created.month
    months = []

    # loop over years and months
    for y in range(year, fyear-1, -1):
        start, end = 12, 0
        if y == year: start = month
        if y == fyear: end = fmonth-1

        for m in range(start, end, -1):
            months.append((y, m, month_name[m]))
    return months

def month(request, year, month):
    """Monthly archive."""
    posts = Post.objects.filter(created__year=year, created__month=month)
    return render_to_response("list.html", dict(post_list=posts, user=request.user,
                                                months=mkmonth_lst(), archive=True))

blog/templates/base.html
{% load static %}
{% load staticfiles %}
<html>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> 
<head>
<script src="js/jquery-3.1.0.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<link type="text/css" href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet" media="screen,projection"/>
<title>Blog</title>
    
 
    
</head>
<body style="background-color:;">
       <!-- Second navbar for profile settings -->
    <div>
    <nav class="navbar navbar-inverse">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-4">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="http://127.0.0.1:8000/">Dante's Blog</a>
        </div>
    
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbar-collapse-4">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="http://127.0.0.1:8000/post/13/">Calculadora</a></li>
            <li><a href="http://127.0.0.1:8000/post/12/">Cambio de Moneda</a></li>
            <li><a href="http://127.0.0.1:8000/post/11/">Formulario</a></li>
            <li><a href="http://127.0.0.1:8000/post/10/">Imagenes</a></li>
            <li><a href="http://127.0.0.1:8000/post/9/">Cronometro</a></li>
           
          </ul>
          <ul class="collapse nav navbar-nav nav-collapse slide-down" role="search" id="nav-collapse4">
            <li><a href="#">Support</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><img class="img-circle" src="https://pbs.twimg.com/profile_images/588909533428322304/Gxuyp46N.jpg" alt="maridlcrmn" width="20" /> Maridlcrmn <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">My profile</a></li>
                <li><a href="#">Favorited</a></li>
                <li><a href="#">Settings</a></li>
                <li class="divider"></li>
                <li><a href="#">Logout</a></li>
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container -->
    </nav><!-- /.navbar -->
</div><!-- /.container-fluid -->


    {% block content %}{% endblock %}
</body>
    

</html>

blog/templates/calculadora.html
{% load static %}
{% load staticfiles %}
<html>
    <head>
    <!--  CON EL CSS NO ANDAN LOS COMENTARIOS   <link href="{% static 'css/calcu.css' %}" type="text/css" rel="stylesheet">-->
    </head>
    <body>
        <div class="primero">
        
    
    </div>
    <div class="calcu">
    <form name="fo" class="fondoCalc">
    <link href="{% static 'css/primero.css' %}" id="cssArchivo" rel="stylesheet" type="text/css" />

        
        <select name="cssCambiar" onChange="changeCss();">
            <option value="{% static 'css/primero.css' %}">Comun</option>
            <option value="{% static 'css/segundo.css'%}">Redondo</option>
            <option value="{% static 'css/tercero.css'%}">Rustica</option>
        </select>
   
    <table>
    <td class=inputstyle colspan="5"><input type="text" name="valores" id="valores" onkeypress ="return solonumeros(event)" ></td> 
    
    <tr>
    
    <td><input type="button" value="7" onclick="print(value)" ></td>
    <td><input type="button" value="8" onclick="print(value)" ></td>
    <td><input type="button" value="9" onclick="print(value)" ></td>
    <td><input type="button" value="+" onclick="print(value)" ></td>
    <td><input type="button" value="-" onclick="print(value)" ></td>
     </tr>
    <tr>
    <td><input type="button" value="4" onclick="print(value)" ></td>
    <td><input type="button" value="5" onclick="print(value)" ></td>
    <td><input type="button" value="6" onclick="print(value)" ></td>
    <td><input type="button" value="*" onclick="print(value)" ></td>
    <td><input type="button" value="/" onclick="print(value)" ></td>
    </tr>
    <tr>
    <td><input type="button" value="1" onclick="print(value)" ></td>
    <td><input type="button" value="2" onclick="print(value)" ></td>
    <td><input type="button" value="3" onclick="print(value)" ></td>
    <td><input type="button" value="(" onclick="print(value)" ></td>
    <td><input type="button" value=")" onclick="print(value)" ></td>
    </tr>    
    <tr>
    <td><input type="button" value="." onclick="print(value)" ></td>
    <td><input type="button" value="0" onclick="print(value)" ></td>
    <td><input type="button" value="<-" onclick="borrar()" ></td>
    <td><input type="button" value="C" onclick="borrartodo()" ></td>
    <td><input type="button" value="=" onclick="resultado()" ></td>
    </tr>
        
    </table>
    <br>
    
    
    
    </form>
    </div>
    </body>

    
    
<script >
    
 
    var res="";
    
    function borrartodo(){
        document.fo.valores.value="";
    }
    
    function borrar(){
        
        var anterior= document.fo.valores.value;
        
        var nuevo=anterior.substring(0,anterior.length-1);
        
        document.getElementById("valores").value=nuevo;
        
    }
    
    function resultado(){
    
        
           
        res = document.fo.valores.value;
        
        document.getElementById("valores").value=res;
        eval(res);
        
        
    
        document.fo.valores.value=eval(res);
        
        
    }
    
    function solonumeros(e){
        
        key=e.keyCode || e.which;
        
        teclado=String.fromCharCode(key);
        
        numeros="0123456789+-*/().";
       
        
        if(numeros.indexOf(teclado)==-1 ){
            return false;
        }
    }
        
    function print(num){
            
        
                
        var anterior= document.fo.valores.value;
        
        document.getElementById("valores").value=anterior+num;
   
    }
    
    function changeCss(){
        var link = document.getElementById("cssArchivo");
        var css = document.fo.cssCambiar;
        link.href = css.value;      
    };
    
    
</script>


</html>

blog/templates/cambio.html
{% load static %}
{% load staticfiles %}
<html>
<body>
<form name="fo">
    
    <td  colspan="5"><input onkeypress="return solonumeros(event)" type="text" name="valores1" id="valores1" ></td> 
    
    <select name="monedas1" onclick="cambio()" >
            <option value="1">Dolares</option>
            <option value="1.13">Euro</option>
            <option value="0.27">Reales</option>
            <option value="0.0677">Pesos Argentinos</option>
            <option value="0.0015">Chilenos</option>
            <option value="0.031">Uruguayos</option>
        </select><br><br><br><br><br><br><br>
    
    
    <td  colspan="5"><input onkeypress="return solonumeros2(event)" type="text" name="valores2" id="valores2" ></td>
    
    <select name="monedas2" onclick="cambio()" >
            <option value="1">Dolares</option>
            <option value="1.13">Euro</option>
            <option value="0.27">Reales</option>
            <option value="0.0677">Pesos Argentinos</option>
            <option value="0.0015">Chilenos</option>
            <option value="0.031">Uruguayos</option>
        </select>
    
    <input onclick="borrar()" value="Borrar" type="button" id="button">
    
     <br>
    
    
    
    
    
</form>
</body>
    
<script>
    
    function borrar(){
        document.fo.valores1.value= "";
        document.fo.valores2.value= "";
    }

    function solonumeros(e){
        
        key=e.keyCode || e.which;
        
        teclado=String.fromCharCode(key);
        
        numeros="0123456789.";
       
        
        if(numeros.indexOf(teclado)==-1 ){
            return false;
        }
    }
    
    function solonumeros2(e){
        
        key=e.keyCode || e.which;
        
        teclado=String.fromCharCode(key);
        
        numeros="";
       
        
        if(numeros.indexOf(teclado)==-1 ){
            return false;
        }
    }
    
    
    function cambio(){
        var cambiar = document.fo.valores1.value;
        
        var ayuda1 = document.fo.monedas1.value;
        
        var ayuda2 = document.fo.monedas2.value;
        
        var pri =eval(cambiar*ayuda1);
        var seg =eval(pri/ayuda2);
        
        document.getElementById("valores2").value=seg;
        
    }
    
</script>
    
    
</html>

blog/templates/chiste.html
{% load static %}
{% load staticfiles %}
<html>

    <head>
    </head> 
    
    <body>
    
        <button id="btn" onmouseover="random()">Clickeame</button>
        Username: <textarea></textarea> <br>
        Password : <textarea></textarea><br><br>
        
        <script>
            
            function random() {
            
                var div = document.getElementById("btn");
                var a = Math.random();
                var a = a*500;
                var b = Math.random();
                var b = b*200;
                console.log(a);
                div.style.left = a;
                div.style.top = b;
                
            }
        
        
        </script>
        
        <style type="text/css">
        
            button{
    
                position: absolute;    
                top: 50%;
                right: 50%;

            }
        </style>
        
    </body>
    
</html>

blog/templates/cronometro.html
{% load static %}
{% load staticfiles %}
<html>
<body>
    
    <div id="cronometro">
        
        <div id="reloj">
        0 : 00 : 00 : 000
        </div>

        <form name="cron" action="#">
        <input type="button" value="Empezar" name="boton1"   />
        <input type="button" value="Parar" name="boton2"  /> <br/>

        </form>
        
    </div>
    
<script>
       
    window.onload = function() {

    visor=document.getElementById("reloj"); //localizar pantalla del reloj
    
    document.cron.boton1.onclick = activo; 
    document.cron.boton2.onclick = pausa;
    //estado inicial de los botones
    document.cron.boton1.disabled=false;
    document.cron.boton2.disabled=true;
        
    var marcha=0; //control del temporizador
    var cro=0;    //estado inicial del cronómetro.
    }
    
    
    
    //botón Empezar / Reiniciar
    function activo (){   
         if (document.cron.boton1.value=="Empezar") { //botón en "Empezar"
            empezar() //ir  la función empezar
            }
         else {  //Botón en "Reiniciar"
            reiniciar()  //ir a la función reiniciar
            }
         }
    //botón pausa / continuar
    function pausa (){ 
         if (marcha==0) { //con el boton en "continuar"
            continuar() //ir a la función continuar
            }
         else {  //con el botón en "parar"
            parar()  //ir a la funcion parar
            }
         }
    
    //Botón 1: Estado empezar: Poner en marcha el crono
    function empezar() {
          emp=new Date(); //fecha inicial (en el momento de pulsar)
          elcrono=setInterval(tiempo,10); //poner en marcha el temporizador.
          marcha=1; //indicamos que se ha puesto en marcha.
          document.cron.boton1.value="Reiniciar"; //Cambiar estado del botón
          document.cron.boton2.disabled=false; //activar botón de pausa
          }
    
    
    //función del temporizador  
    function tiempo() { 
         actual=new Date(); //fecha a cada instante 
            //tiempo del crono (cro) = fecha instante (actual) - fecha inicial (emp)    
         cro=actual-emp; //milisegundos transcurridos.  
         cr=new Date(); //pasamos el num. de milisegundos a objeto fecha.   
         cr.setTime(cro); 
            //obtener los distintos formatos de la fecha:   
         cs=cr.getMilliseconds(); //milisegundos    
         //cs=cs/10; //paso a centésimas de segundo.    
         cs=Math.round(cs); //redondear las centésimas  
         sg=cr.getSeconds(); //segundos     
         mn=cr.getMinutes(); //minutos  
         ho=cr.getHours()-21; //horas   
            //poner siempre 2 cifras en los números          
         if (cs<10) {cs="00"+cs;} 
         if (cs<100) {cs="0"+cs;} 
         if (sg<10) {sg="0"+sg;} 
         if (mn<10) {mn="0"+mn;} 
        
            //llevar resultado al visor.             
         visor.innerHTML=ho+" : "+mn+" : "+sg+" : "+cs; 
         }
    
    //parar el cronómetro
    function parar() { 
         clearInterval(elcrono); //parar el crono
         marcha=0; //indicar que está parado.
         document.cron.boton2.value="Continuar"; //cambiar el estado del botón
         }  
    
    //Continuar una cuenta empezada y parada.
    function continuar() {
         emp2=new Date(); //fecha actual
         emp2=emp2.getTime(); //pasar a tiempo Unix
         emp3=emp2-cro; //restar tiempo anterior
         emp=new Date(); //nueva fecha inicial para pasar al temporizador 
         emp.setTime(emp3); //datos para nueva fecha inicial.
         elcrono=setInterval(tiempo,10); //activar temporizador
         marcha=1; //indicar que esta en marcha
         document.cron.boton2.value="Parar"; //Cambiar estado del botón
         document.cron.boton1.disabled=false; //activar boton 1 si estuviera desactivado
         }
    
    
    //Volver al estado inicial
    function reiniciar() {
         if (marcha==1) {  //si el cronómetro está en marcha:
             clearInterval(elcrono); //parar el crono
             marcha=0;  //indicar que está parado
             }
                 //en cualquier caso volvemos a los valores iniciales
         cro=0; //tiempo transcurrido a cero
         visor.innerHTML = "0 00 00 00"; //visor a cero
         document.cron.boton1.value="Empezar"; //estado inicial primer botón
         document.cron.boton2.value="Parar"; //estado inicial segundo botón
         document.cron.boton2.disabled=true;  //segundo botón desactivado    
         }  


</script>
    
</body>
</html>

blog/templates/img.html
{% load static %}
{% load staticfiles %}
<html>
    
<body>
    
<p align="center">
    
<img src="" id="imagen" > <br>

<progress id="barra"></progress>
<span id="valor"></span>  % <br><br>   
    
</body>
    
  <style>
    
      img{
          
      }
  </style>  
    
<script>
    
    
    
    var tiempo = 5000;
    
    var numeroImagenes = 5 ;
    
    
    var maximo = 100;
    
    var j=1;
    
    
    document.getElementById("barra").setAttribute("value",0);
    document.getElementById("barra").setAttribute("max",maximo);
    
    function cambiarImagen(){
        
        
        var numero = Math.floor(Math.random() * numeroImagenes ) + 1;
        
        var imagenes = new Array( "{% static 'Images/' %}" + numero + ".jpg" );
        
        
        var ayuda = Math.floor((0));
        
        
        document.getElementById("imagen").src=imagenes[ayuda];

    }
    
    
    function aumentar(){
            
            document.getElementById("valor").innerHTML = j;
            
            document.getElementById("barra").setAttribute("value",j++);
        
            if (j<10){ j= "0"+j; }
            
            
            if (j==maximo){
                
                j=1;
                
                cambiarImagen();
            }
            
        } 
     
    
    
    cambiarImagen();
         
    
    setInterval(aumentar,50);
 
    
    
</script>    

</html>

blog/templates/list.html
{% extends "base.html" %}
{% block sidebar %}
{% load static %}
{% load staticfiles %}
<link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
    <style type="text/css">
        #sidebar { float: right; border: 1px dotted #ccc; padding: 4px; }
        a { margin-left: 15px; }

    </style>
    <div id="sidebar">
        Monthly Archive
        <p>
        {% for month in months %}
            {% ifchanged month.0 %} {{ month.0 }} <br /> {% endifchanged %}

        {% endfor %}
        </p>
    </div>
{% endblock %}

{% block content %}

{% for post in post_list %}
<div class="container" ALIGN=center>
    <div class="left-panel">
        <div class="col-xs-12 col-sm-6 col-lg-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="col-md-12">
                        <div class="thumbnail">
                            <a href="#"><img src="{% static 'fotos/'%}{{post.nombre_imagen}}" alt=""/></a>
                        </div>
                        <div class="icerik-bilgi">
                            <a><h2>{{post.title}}</h2></a>
                            <p>Click en el boton debajo para saber mas sobre este post</p>
                            <div class="btn-group">
                                <a class="btn btn-social btn-facebook" href="#" data-toggle="tooltip" title="Share Facebook"><i class="fa fa-facebook"></i></a>
                                <a class="btn btn-social btn-twitter" href="#" data-toggle="tooltip" title="Share Twitter"><i class="fa fa-twitter"></i></a>
                                <a class="btn btn-social btn-google" href="#" data-toggle="tooltip" title="Share Google"><i class="fa fa-google"></i></a>
                            </div>
                            <a href="{% url 'index:post' post.id %}">
                             <button type="button" class="btn btn-primary "  >
                                <span class="btn btn-google">Detalles<i class="fa fa-chevron-right"></i></span>
                             </button>
                             </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    
</div>
<script>
    $(document).ready(function(){
        $('[data-toggle="tooltip"]').tooltip();   
    });
</script>
</div>{% endfor %}

        <!-- Next/Prev page links  -->
        {% if not archive and posts.object_list and posts.paginator.num_pages > 1 %}
        <div class="pagination">
            <span class="step-links">
                {% if posts.has_previous %}
                    <a href= "?page={{ posts.previous_page_number }}">Entradas mas nuevas &lt;&lt; </a>
                {% endif %}

                <span class="current">
                    &nbsp;Pagina {{ posts.number }} de {{ posts.paginator.num_pages }}
                </span>

                {% if posts.has_next %}
                    <a href="?page={{ posts.next_page_number }}"> &gt;&gt; Post mas viejitos</a>
                {% endif %}
            </span>
        </div>
        {% endif %}



{% endblock %}

blog/templates/post.html
{% extends "base.html" %}
{% load static %}
{% load staticfiles %}
{% block content %}
<script src="http://www.w3schools.com/lib/w3data.js"></script>
<link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
    <style type="text/css">
        .main { margin-left: 25px; margin-top: 30px; }
        .time { font-size: 0.8em; margin-top: 2px; }
        .comment { border: 1px solid #eee; padding: 4px; margin-bottom: 12px; }
        .body { font-size: 1.1em; margin-top: 2px; }
        .messages { margin-left: 20px; }
        .title { font-size: 14px; margin-top: 20px; border-bottom: 1px solid #ccc;color: #000; padding-left: 4px; }

        #addc { width: 508px; background: #f5f5f5; padding: 3px; padding-bottom: 8px;
            border-bottom: 1px dotted #aaa;
            }
        #cform { background: #f5f5f5; width: 506px; padding: 4px; padding-bottom: 0px; }
        #submit { text-align: right; margin-right: 50px; width: 500px; margin-top: -5px; }

        ul { margin-bottom: 30px; }

    </style>
    <div class="main">

        <!-- Messages  -->
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}

        <!-- Post  -->
        <ul>
            <div class="blog-title" style="margin-top:3%;margin-left:40%"><h3>{{ post.title }}</h3></div>
            <ul style="margin-bottom:5%" >
             <div>
                 {% if post.url_post|length > 0 %}
                 {% include post.url_post %}
                 {% else %}
                 
                 {% endif %}
                 {{post.body}}
                
                </div>
                
                <div style="margin-bottom:10%" w3-include-html="{% static 'tp/ej'%}{{post.id}}.html"></object></div>

            <!-- Comments  -->
            {% if comments %}
                <p style="margin-bottom:2%">Comentarios:</p>
            {% endif %}

            <form action="" method="POST">{% csrf_token %}
            {% for comment in comments %}
                <div class="comment">
                    <div class="time"> {{ comment.author }}    | {{ comment.created }}</div>
                    <div class="body">{{ comment.body|linebreaks }}</div>
                    {% if user.is_staff %}

                    {% endif %}
                </div>
            {% endfor %}

            {% if user.is_staff and comments %}
                
                <br />
            {% endif %}
            </form>

            
            <!-- Comment form  -->
            <form style="background-color:green;width:100%;height:30%;border-radius:1%" action="" method="POST">
            
                {% csrf_token %}
                <div style="margin-bottom:0%"class="input-group">
				<div  style="margin-top:5%;margin-left:5%;width:15%;color:black"><h5>Comente:<h5/></div>
                    <input style="width:20%;margin-left:11%" type="text" length="10" id="input_text" class="form-control" placeholder="Autor" name='author' aria-describedby="basic-addon1"/>
                    <textarea style="width:41%;height:25%;margin-left:11%" length="120" id="textarea1" class="materialize-textarea" placeholder="Comentario" name='content' aria-describedby="basic-addon1"></textarea>
                    <br>
                <div style="margin-left:-30%;margin-top:5%" id="submit"><input type="submit" value="Enviar"></div>
</div>

            
            </form>
        </ul>

    </div>

{% endblock %}